spring:
  datasource:
    url: jdbc:postgresql://snippet_manager_db:5432/snippet-manager-db
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth0:
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  domain: ${AUTH0_DOMAIN}
  audience: ${AUTH0_AUDIENCE}

stream:
  formatter: "format-stream"

groups:
  formatter: "format-groups"
  linter: "linter-groups"